/**
 * Lightweight keyword check for messages that look like a user is in
 * imminent crisis. Hits trigger:
 *   1. An incident row in `crisis_flags` for care-team follow-up.
 *   2. A care-team notification email.
 * The chat reply itself is still generated by Claude, with the system
 * prompt's crisis-handling instruction already in place. This is a pre-check
 * that runs alongside, not a replacement.
 */

const EN_KEYWORDS = [
  "kill myself",
  "kill my self",
  "killmyself",
  "kms",
  "want to die",
  "wanna die",
  "want to be dead",
  "ready to die",
  "ending my life",
  "end my life",
  "end it all",
  "ending it all",
  "ending it tonight",
  "suicide",
  "commit suicide",
  "hurt myself",
  "harm myself",
  "cut myself",
  "cutting myself",
  "self harm",
  "self-harm",
  "no point in living",
  "no reason to live",
  "better off dead",
  "better off without me",
  "no one would miss me",
  "going to kill",
  "going to hurt",
];

const ES_KEYWORDS = [
  "matarme",
  "me quiero matar",
  "quiero matarme",
  "quiero morir",
  "quiero estar muerto",
  "quiero estar muerta",
  "quitarme la vida",
  "acabar con todo",
  "acabar con mi vida",
  "suicidio",
  "suicidarme",
  "hacerme daño",
  "hacerme dano",
  "lastimarme",
  "cortarme",
  "cortándome",
  "cortandome",
  "no tiene sentido vivir",
  "mejor sin mí",
  "mejor sin mi",
  "mejor muerto",
  "mejor muerta",
  "voy a matar",
  "voy a hacerle daño",
  "nadie me extrañaría",
  "nadie me extranaria",
];

export type CrisisDetection = {
  triggered: boolean;
  matched: string[];
};

export function detectCrisis(text: string): CrisisDetection {
  const lower = text.toLowerCase();
  const matched: string[] = [];
  for (const kw of [...EN_KEYWORDS, ...ES_KEYWORDS]) {
    if (lower.includes(kw)) matched.push(kw);
  }
  return { triggered: matched.length > 0, matched };
}
