/**
 * Face generation pipeline — FLUX 1.1 Pro on Replicate → Supabase Storage
 * → oracles.avatar_url.
 *
 * Model choice: black-forest-labs/flux-1.1-pro (~$0.04/image). NOT Schnell
 * — Schnell's few-step distillation is exactly where the "missing nose /
 * melted eye" failure mode lives, and Wilson's rule on anatomy is hard.
 * (Dev is a middle option, but Pro's anatomy is at least as good and it
 * runs behind BFL's tuned serving stack, so Pro it is.)
 *
 * Designed to be called fire-and-forget (from `after()` callbacks): it
 * NEVER throws. Every failure lands in oracles.face_generation_status /
 * face_generation_error and comes back as { ok: false }.
 *
 * Durability: Replicate output URLs expire after a few weeks, so we copy
 * the bytes into the public `avatars` bucket (path: <oracleId>.png) and
 * store OUR CDN URL on the oracle row.
 */

import { createHash } from "node:crypto";
import Replicate, { type FileOutput } from "replicate";
import { createAdminClient } from "@/lib/supabase/admin";
import type { Traits } from "@/lib/identity/formula";
import { buildFacePrompt, faceSeed } from "./prompt";

const FACE_MODEL = "black-forest-labs/flux-1.1-pro" as const;

/** Hard cap on one generation round-trip. Flux Pro runs 15–40s. */
const GENERATION_TIMEOUT_MS = 90_000;

/**
 * Face-uniqueness retries (Wilson: "no two of the same"). If the
 * generated bytes hash-collide with another oracle's avatar_hash we
 * regenerate with a deterministically mutated seed via
 * faceSeed(oracleId, attempt) — the retry ladder itself is reproducible.
 * 3 retries AFTER the original attempt (seeds faceSeed(id, 1..3)), so up
 * to 4 generations total. Flux with a different seed produces a different
 * image, so even one retry colliding again is astronomically improbable.
 */
const MAX_COLLISION_RETRIES = 3;

export type FaceResult =
  | { ok: true; url: string }
  | { ok: false; error: string };

/**
 * Generate a portrait for `oracleId` and persist it.
 *
 * Idempotent: if avatar_url is already set, returns it untouched unless
 * `opts.force` (explicit retry/regenerate). The seed is derived from the
 * oracle id, so a forced regeneration reproduces the same face barring
 * model version drift.
 */
export async function generateAndSaveFace(
  oracleId: string,
  traits: Traits,
  opts?: { force?: boolean },
): Promise<FaceResult> {
  const admin = createAdminClient();

  try {
    // 1. Idempotency gate.
    const { data: oracle, error: readError } = await admin
      .from("oracles")
      .select("id, avatar_url")
      .eq("id", oracleId)
      .maybeSingle();
    if (readError) {
      throw new Error(`oracle read failed: ${readError.message}`);
    }
    if (!oracle) {
      // No row → nothing to attach a status to either.
      return { ok: false, error: `oracle ${oracleId} not found` };
    }
    if (oracle.avatar_url && !opts?.force) {
      return { ok: true, url: oracle.avatar_url };
    }

    // 2. Mark in-flight.
    await admin
      .from("oracles")
      .update({ face_generation_status: "pending", face_generation_error: null })
      .eq("id", oracleId);

    // 3. Build the prompt. negativePrompt is intentionally unused here:
    //    FLUX has no negative_prompt input (see prompt.ts header) —
    //    anatomy safety rides on the positive grounding + safety_tolerance.
    const { prompt } = buildFacePrompt(traits, oracleId);

    const replicate = new Replicate({
      auth: process.env.REPLICATE_API_TOKEN,
    });

    // 4/5. Generate → hash → uniqueness check. Wilson's "no two of the
    //    same": if the bytes hash-collide with ANOTHER oracle's
    //    avatar_hash, regenerate with the deterministically mutated seed
    //    for that attempt (faceSeed(id, N) — the retry ladder itself is
    //    reproducible). The 0058 partial unique index is the DB backstop
    //    if this app-level check ever race-conditions.
    let bytes: Buffer | null = null;
    let avatarHash: string | null = null;
    let collided = false;
    for (let attempt = 0; attempt <= MAX_COLLISION_RETRIES; attempt++) {
      const candidate = await runFluxPortrait(
        replicate,
        prompt,
        faceSeed(oracleId, attempt),
      );
      const hash = createHash("sha256").update(candidate).digest("hex");
      const { data: clash, error: clashError } = await admin
        .from("oracles")
        .select("id")
        .eq("avatar_hash", hash)
        .neq("id", oracleId)
        .limit(1)
        .maybeSingle();
      if (clashError) {
        throw new Error(`avatar_hash check failed: ${clashError.message}`);
      }
      bytes = candidate;
      avatarHash = hash;
      collided = Boolean(clash);
      if (!collided) break;
      console.warn(
        attempt < MAX_COLLISION_RETRIES
          ? `[faces] avatar_hash collision for ${oracleId} with oracle ${clash?.id} (attempt ${attempt}, ${MAX_COLLISION_RETRIES - attempt} retries left); regenerating with mutated seed`
          : `[faces] avatar_hash collision for ${oracleId} with oracle ${clash?.id} on final retry; accepting with '-collision' hash suffix`,
      );
    }
    if (!bytes || !avatarHash) {
      throw new Error("Replicate returned no output");
    }
    if (collided) {
      // Documented edge case (see 0058_avatars.sql): every retry collided.
      // Suffix the hash so the partial unique index doesn't block the
      // write — astronomically improbable, but never strand the oracle.
      avatarHash = `${avatarHash}-collision`;
    }

    // 6. Persist to our bucket; upsert so a forced regen overwrites.
    const storagePath = `${oracleId}.png`;
    const { error: uploadError } = await admin.storage
      .from("avatars")
      .upload(storagePath, bytes, {
        contentType: "image/png",
        upsert: true,
      });
    if (uploadError) {
      throw new Error(`storage upload failed: ${uploadError.message}`);
    }
    const { data: pub } = admin.storage
      .from("avatars")
      .getPublicUrl(storagePath);
    // Cache-buster so a forced regen isn't masked by the CDN serving the
    // old object from the same path.
    const publicUrl = `${pub.publicUrl}?v=${Date.now()}`;

    // 7. Success. If a concurrent write beat us to this exact hash, the
    //    0058 unique index rejects the update → we land in the failed
    //    (retryable) path, exactly as the migration documents.
    const { error: updateError } = await admin
      .from("oracles")
      .update({
        avatar_url: publicUrl,
        avatar_hash: avatarHash,
        face_generation_status: "succeeded",
        face_generation_error: null,
      })
      .eq("id", oracleId);
    if (updateError) {
      throw new Error(`oracle update failed: ${updateError.message}`);
    }

    return { ok: true, url: publicUrl };
  } catch (err) {
    const message =
      err instanceof Error ? err.message : String(err ?? "unknown error");
    console.error(`[faces] generation failed for ${oracleId}:`, err);
    // Best-effort status write — never let the error path itself throw.
    try {
      await admin
        .from("oracles")
        .update({
          face_generation_status: "failed",
          face_generation_error: message.slice(0, 500),
        })
        .eq("id", oracleId);
    } catch (statusErr) {
      console.error(`[faces] could not record failure for ${oracleId}:`, statusErr);
    }
    return { ok: false, error: message };
  }
}

/**
 * One FLUX 1.1 Pro run → PNG bytes. `wait` blocks server-side (60s is
 * Replicate's block ceiling; the client falls back to polling after),
 * and the abort signal caps the whole round-trip at 90s.
 */
async function runFluxPortrait(
  replicate: Replicate,
  prompt: string,
  seed: number,
): Promise<Buffer> {
  const output = await replicate.run(FACE_MODEL, {
    input: {
      prompt,
      aspect_ratio: "1:1",
      seed,
      output_format: "png",
      output_quality: 100,
      safety_tolerance: 1, // strictest — built-in NSFW filter
      prompt_upsampling: false, // keep the prompt deterministic too
    },
    wait: { mode: "block", timeout: 60 },
    signal: AbortSignal.timeout(GENERATION_TIMEOUT_MS),
  });

  // replicate@1.x returns FileOutput (a stream with .blob()/.url());
  // older shapes are a URL string or an array.
  const first = Array.isArray(output) ? output[0] : output;
  if (!first) {
    throw new Error("Replicate returned no output");
  }
  if (typeof (first as FileOutput).blob === "function") {
    const blob = await (first as FileOutput).blob();
    return Buffer.from(await blob.arrayBuffer());
  }
  const res = await fetch(String(first), {
    signal: AbortSignal.timeout(30_000),
  });
  if (!res.ok) {
    throw new Error(`could not download generated image (${res.status})`);
  }
  return Buffer.from(await res.arrayBuffer());
}
