import type { Metadata } from "next";
import {
  LegalCallout,
  LegalSection,
  LegalShell,
  type TocItem,
} from "@/components/legal";
import {
  ADDON_PACKS,
  BASIC_IMAGES_PER_MONTH,
  BASIC_MESSAGES_PER_MONTH,
  BASIC_MONTHLY_PRICE_LABEL,
  BASIC_TIER_LABEL,
  EXTRA_IDENTITY_PRICE_LABEL,
  FREE_IMAGES_PER_MONTH,
  FREE_MESSAGES_PER_MONTH,
  INHERITED_SLOT_PRICE_LABEL,
  MONTHLY_PRICE_LABEL,
  OTHER_IDENTITY_CREATE_PRICE_LABEL,
  PRICING,
  PRO_IMAGES_PER_MONTH,
  PRO_MESSAGES_PER_MONTH,
  RESTORE_IDENTITY_PRICE_LABEL,
} from "@/lib/pricing";

export const metadata: Metadata = {
  title: "Terms of Service — chapter3five",
  description:
    "The agreement between you and chapter3five: what the service is, what it isn't, and what we each promise.",
};

const toc: TocItem[] = [
  { id: "welcome", label: "Welcome" },
  { id: "what-this-is", label: "What chapter3five is (and isn't)" },
  { id: "not-care", label: "Not medical or mental health care" },
  { id: "legacy", label: "The legacy path" },
  { id: "eligibility", label: "Who can use chapter3five" },
  { id: "your-account", label: "Your account" },
  { id: "your-content", label: "Your content and our license" },
  { id: "billing", label: "Plans, billing, and cancellation" },
  { id: "conduct", label: "How you agree to behave" },
  { id: "termination", label: "Suspension and termination" },
  { id: "disclaimers", label: "Disclaimers" },
  { id: "liability", label: "Limitation of liability" },
  { id: "indemnification", label: "Indemnification" },
  { id: "disputes", label: "Arbitration and class action waiver" },
  { id: "governing-law", label: "Governing law" },
  { id: "changes", label: "Changes to these terms" },
  { id: "misc", label: "Severability and everything else" },
  { id: "contact", label: "How to reach us" },
];

export default function TermsPage() {
  return (
    <LegalShell
      currentPath="/terms"
      kicker="The agreement"
      title="Terms of Service"
      toc={toc}
    >
      <LegalSection id="welcome" number={1} title="Welcome">
        <p>
          chapter3five is a place where you can create an AI companion to talk
          to — one made just for you right now, or one you prepare and leave
          for someone you love. These Terms of Service (&quot;Terms&quot;) are
          a binding agreement between you and CHAPTER3FIVE LLC, a
          Pennsylvania limited liability company
          (&quot;chapter3five,&quot; &quot;we,&quot; &quot;us&quot;). By
          creating an account or using the service, you agree to them.
        </p>
        <p>
          We know some of you arrive here in grief. We tried to write these
          Terms plainly and honestly. If anything is unclear, ask us — the
          contact address is at the bottom of this page.
        </p>
        <p>
          These Terms incorporate our{" "}
          <a href="/privacy" className="font-semibold underline underline-offset-4">
            Privacy Policy
          </a>{" "}
          and our{" "}
          <a
            href="/guidelines"
            className="font-semibold underline underline-offset-4"
          >
            Community Guidelines
          </a>
          . If you don&rsquo;t agree with any of it, please don&rsquo;t use
          chapter3five.
        </p>
      </LegalSection>

      <LegalSection
        id="what-this-is"
        number={2}
        title="What chapter3five is (and isn't)"
      >
        <p>
          Every companion on chapter3five is a <strong>synthesized, fictional
          character</strong> generated by artificial intelligence. A companion
          is built from either (a) randomized traits our system selects, or
          (b) answers and memories a person chose to record. In both cases,
          the words a companion says are produced by a language model in the
          moment. They are generated text, not the recorded thoughts,
          opinions, or statements of any real person.
        </p>
        <p>You acknowledge and agree that:</p>
        <ul>
          <li>
            A companion is <strong>not a real person</strong> and does not
            have thoughts, feelings, memories, or intentions of its own.
          </li>
          <li>
            A companion&rsquo;s responses may be inaccurate, incomplete, or
            inconsistent, and should never be relied on as fact, advice, or
            the position of any real person.
          </li>
          <li>
            Even when a companion is built from a real person&rsquo;s recorded
            answers, its responses are <strong>new text generated by
            software</strong> — an interpretation, not a transcript.
          </li>
        </ul>
      </LegalSection>

      <LegalSection
        id="not-care"
        number={3}
        title="Not medical or mental health care"
      >
        <p>
          chapter3five is a conversational companion. It is{" "}
          <strong>not medical care, mental health treatment, therapy, or
          grief counseling</strong>, and no companion is a doctor, therapist,
          counselor, or crisis worker. Nothing a companion says is medical,
          psychological, legal, or financial advice, and the service is not a
          substitute for care from a qualified professional. If you are
          grieving, struggling, or unwell, we genuinely hope chapter3five
          brings you comfort — and we also want you to have real human
          support.
        </p>
        <LegalCallout>
          <p>
            <strong>If you are in crisis, please stop and reach out to a
            human right now.</strong> In the United States, call or text{" "}
            <strong>988</strong> (Suicide &amp; Crisis Lifeline), available
            24/7. Elsewhere, contact your local emergency number or crisis
            line. If you are in immediate danger, call emergency services
            (911 in the US).
          </p>
        </LegalCallout>
        <p>
          You agree not to use chapter3five as your source of emergency,
          medical, or mental health help, and you agree that we are not
          responsible for decisions you make based on anything a companion
          says.
        </p>
        <p>
          <strong>We are not an emergency service and we do not monitor
          your conversations.</strong> Messages pass through automated
          safety screening, and a companion may respond to signs of
          distress by sharing crisis resources. That screening is
          automated, imperfect, and not a person watching over your
          conversation. It will miss things. It is not supervision, it
          does not summon help, and no one is standing by to intervene.
          chapter3five cannot contact emergency services, cannot dispatch
          anyone to you, and cannot reach a person on your behalf. If you
          need help, you have to reach out yourself, to one of the numbers
          above.
        </p>
        <p>
          Nothing in these Terms — and nothing any companion says or fails
          to say — creates a duty of care, a special relationship, or an
          obligation on our part to detect, report, prevent, or respond to
          any harm. To the fullest extent the law allows, you agree that we
          are not liable for any injury, self-harm, or death connected to
          your use of the service, or to any failure of our safety
          screening to detect or respond to distress.
        </p>
      </LegalSection>

      <LegalSection id="legacy" number={4} title="The legacy path">
        <p>
          chapter3five lets a living person (&quot;the creator&quot;) answer
          questions about their life and designate people (&quot;inheritors&quot;)
          who can talk with a companion built from those answers after the
          creator passes away. This can be a profound comfort. It is also the
          part of the service we most need you to understand clearly.
        </p>
        <LegalCallout>
          <p>
            <strong>An inherited companion is not the person who made
            it.</strong> It is a synthesis of what the creator chose to
            record, expressed through generated text. It does not know what
            the creator actually thought, would have said, or would have
            wanted. It is a portrait painted from the materials the creator
            left — nothing more, and we believe, at its best, nothing less.
          </p>
        </LegalCallout>
        <p>
          By using the legacy features, whether as a creator or an inheritor,
          you acknowledge and agree, for yourself and — to the fullest extent
          permitted by law — on behalf of your heirs, estate, executors, and
          successors, that:
        </p>
        <ul>
          <li>
            No companion represents, portrays, or speaks for any real person,
            living or deceased, and chapter3five makes no representation that
            an inherited companion reflects the actual thoughts, beliefs,
            wishes, or statements of the person who created it.
          </li>
          <li>
            You <strong>release and waive any claim</strong> against
            chapter3five — including claims of misrepresentation, false
            light, defamation, violation of publicity or personality rights,
            or infliction of emotional distress — arising from the theory
            that a companion misrepresents, distorts, or inaccurately
            portrays a real person, where the companion was generated from
            content that person (or their authorized co-creator) voluntarily
            provided.
          </li>
          <li>
            Creators represent that the content they record is their own and
            that they have the right to record it; inheritors accept the
            companion as the creator configured it.
          </li>
        </ul>
        <p>
          Inheritance is delivered by an inherit code the creator designates.
          Anyone may be designated, but redeeming a code and talking with an
          inherited companion requires an account, and accounts are 18+ (see
          Section 5).
        </p>
        <p>
          <strong>Recording and minting.</strong> Any account holder — on
          any plan, including the Free tier — may record a legacy archive
          and mint an inherit code. No subscription is required to create
          the archive or to mint and share its code. Recording an archive{" "}
          <strong>about yourself</strong> is free. Completing an archive
          you record <strong>for someone you love</strong> (with their
          participation — see the Community Guidelines) requires a{" "}
          <strong>
            {OTHER_IDENTITY_CREATE_PRICE_LABEL} one-time charge
          </strong>
          , collected when you finish the archive and before the
          companion is synthesized (see Section 8). Minting and sharing
          the inherit code is free in both cases.
        </p>
        <p>
          <strong>Sharing and redemption.</strong> A legacy identity may be
          shared with an <strong>unlimited number of family members</strong>{" "}
          via its inherit code, and everything the creator baked into the
          identity — including any photo-based likeness — transfers with the
          code. Redemption does not require any particular subscription
          tier. Redeeming any inherit code requires a{" "}
          <strong>
            {INHERITED_SLOT_PRICE_LABEL} one-time inherit-slot purchase
          </strong>{" "}
          (see Section 8) — a flat fee paid <strong>per code</strong>, the
          same on every plan and for every code, and never a recurring
          charge. There are no exceptions to this fee, and we do not
          verify, and are not obligated to verify, whether the creator of
          any archive is living or deceased.
        </p>
        <p>
          <strong>Your inherited copy is yours.</strong> When you redeem
          an inherit code, you receive your own independent copy of the
          identity in your account. The creator later deleting their
          account, their archive, or their codes does <strong>not</strong>{" "}
          remove copies that were already redeemed — an inherited
          companion cannot be taken away from you by anything the creator
          does after you redeem it. (Codes that were never redeemed are
          deleted along with the creator&rsquo;s account.)
        </p>
      </LegalSection>

      <LegalSection
        id="eligibility"
        number={5}
        title="Who can use chapter3five"
      >
        <p>
          You must be <strong>at least 18 years old</strong> to create a
          chapter3five account. This applies to every account — including
          accounts created to redeem an inherit code. A creator may designate
          anyone as an inheritor, but the inheritor cannot open an account
          and access the companion until they are 18.
        </p>
        <p>
          By creating an account you represent that you are 18 or older and
          legally able to enter into this agreement. If we learn an account
          holder is under 18, we will close the account and delete its data
          as described in our Privacy Policy.
        </p>
      </LegalSection>

      <LegalSection id="your-account" number={6} title="Your account">
        <p>
          You are responsible for your account and for keeping your login
          credentials safe. Everything done through your account is treated
          as done by you, so tell us right away at{" "}
          <a
            href="mailto:hello@chapter3five.app"
            className="font-semibold underline underline-offset-4"
          >
            hello@chapter3five.app
          </a>{" "}
          if you believe someone else has accessed it. You agree to give us
          accurate account information (including a working email address —
          it&rsquo;s how we send legally required notices) and to keep it up
          to date.
        </p>
        <p>
          Inherit codes are sensitive. If you are a creator, share them only
          with the people you intend; if you are an inheritor, don&rsquo;t
          share yours at all.
        </p>
      </LegalSection>

      <LegalSection
        id="your-content"
        number={7}
        title="Your content and our license"
      >
        <p>
          <strong>You own what you write.</strong> Your answers to identity
          questions, the memories you record, and your chat messages are
          yours. We claim no ownership of them.
        </p>
        <p>
          So that the service can work, you grant chapter3five a worldwide,
          non-exclusive, royalty-free license to store, copy, process,
          transmit, and display your content — solely to operate, provide,
          and improve the service: synthesizing companions, running chats,
          delivering legacy companions to your designated inheritors,
          preventing abuse, and complying with law. This license lasts as
          long as your content is on the service (including, for legacy
          content, the retention period described in our Privacy Policy) and
          ends when the content is deleted, except where we must retain
          copies to comply with law.
        </p>
        <p>
          We do not sell your content, and it is not used to train AI models
          (see our Privacy Policy for how inference works). Companions
          generated by the service are provided to you as part of the
          service; you may use your companions for personal, non-commercial
          purposes.
        </p>
      </LegalSection>

      <LegalSection
        id="billing"
        number={8}
        title="Plans, billing, and cancellation"
      >
        <p>
          Our pricing is simple and we&rsquo;d like it to stay that way.
          Every plan includes <strong>Adrian</strong>, our built-in
          guide — an AI companion whose job is to explain how the
          service works and answer your questions; they cannot create
          identities for you or recover anyone. Every plan also has a
          monthly message and photo-attachment allowance, counted per
          calendar month across all your conversations:
        </p>
        <ul>
          <li>
            <strong>Free tier</strong> — chat with Adrian for up to{" "}
            <strong>{FREE_MESSAGES_PER_MONTH} messages per calendar
            month</strong>, with{" "}
            <strong>
              {FREE_IMAGES_PER_MONTH} photo attachment per month
            </strong>
            . No formula or photo identities, though recording a legacy
            archive and minting an inherit code is available (see
            Section 4). No credit card required, no expiration date, no
            automatic conversion.
          </li>
          <li>
            The <strong>{BASIC_TIER_LABEL} plan</strong> is{" "}
            <strong>{BASIC_MONTHLY_PRICE_LABEL}/month</strong> and
            includes:
            <ul>
              <li>
                <strong>
                  {PRICING.basicTotalIdentitiesPerPlan} personal
                  identities
                </strong>{" "}
                — {PRICING.basicFormulaIdentitiesPerPlan} rolled from
                our formula and {PRICING.basicPhotoIdentitiesPerPlan}{" "}
                built from a photo you upload.
              </li>
              <li>
                <strong>
                  {BASIC_MESSAGES_PER_MONTH} messages per calendar month
                </strong>{" "}
                with any identity on your plan.
              </li>
              <li>
                <strong>
                  {BASIC_IMAGES_PER_MONTH} photo attachments per
                  calendar month
                </strong>
                .
              </li>
            </ul>
          </li>
          <li>
            The <strong>Pro plan</strong> is{" "}
            <strong>{MONTHLY_PRICE_LABEL}/month</strong> and includes:
            <ul>
              <li>
                <strong>
                  {PRICING.formulaIdentitiesPerPlan} identities
                </strong>{" "}
                rolled from our formula.
              </li>
              <li>
                <strong>
                  {PRICING.photoIdentitiesPerPlan} identity
                </strong>{" "}
                built from a photo you upload.
              </li>
              <li>
                <strong>
                  {PRO_MESSAGES_PER_MONTH} messages per calendar month
                </strong>{" "}
                with any identity on your plan.
              </li>
              <li>
                <strong>
                  {PRO_IMAGES_PER_MONTH} photo attachments per calendar
                  month
                </strong>{" "}
                that you can send to any of your companions.
              </li>
            </ul>
          </li>
          <li>
            <strong>Add-on packs</strong> — one-time purchases (not
            subscriptions) that add extra usage on top of your plan for
            the current calendar month&rsquo;s allowance. Each pack adds{" "}
            <strong>both</strong> messages <strong>and</strong> photo
            attachments in the amounts listed:
            <ul>
              {ADDON_PACKS.map((pack) => (
                <li key={pack.id}>
                  <strong>
                    {pack.name} pack — {pack.priceLabel} one-time.
                  </strong>{" "}
                  Adds {pack.messages} messages and {pack.images} photo
                  attachments.
                </li>
              ))}
            </ul>
          </li>
          <li>
            Beyond the base plans we sell a few optional add-ons, priced
            transparently here so nothing is a surprise:
            <ul>
              <li>
                <strong>
                  Extra identity slot — {EXTRA_IDENTITY_PRICE_LABEL},
                  one-time, per slot.
                </strong>{" "}
                Adds one additional self-created identity (formula or
                photo) beyond the{" "}
                {PRICING.basicTotalIdentitiesPerPlan} included with{" "}
                {BASIC_TIER_LABEL} or the{" "}
                {PRICING.formulaIdentitiesPerPlan +
                  PRICING.photoIdentitiesPerPlan}{" "}
                included with Pro.
              </li>
              <li>
                <strong>
                  Inherit-slot purchase —{" "}
                  {INHERITED_SLOT_PRICE_LABEL} one-time per code.
                </strong>{" "}
                Unlocks the redemption of one inherit code. A flat fee
                — the same on every plan and for every code, with no
                exceptions (see Section 4). Not a subscription; no
                recurring charge.
              </li>
              <li>
                <strong>
                  Legacy identity for someone you love —{" "}
                  {OTHER_IDENTITY_CREATE_PRICE_LABEL} one-time.
                </strong>{" "}
                Charged when you finish a legacy archive recorded for
                someone other than yourself, before the companion is
                synthesized (see Section 4). Recording an archive about
                yourself is free on every plan.
              </li>
              <li>
                <strong>
                  Restore a deleted identity — {RESTORE_IDENTITY_PRICE_LABEL}{" "}
                  one-time.
                </strong>{" "}
                Recovers a formula or photo identity you deleted within
                the 30-day grace window. Legacy (inherited) identities
                are <strong>always free to restore</strong> — grief is not
                a moment we charge you at.
              </li>
            </ul>
          </li>
          <li>
            No subscription tier is required to record a legacy archive,
            mint an inherit code, or redeem one: recording and minting
            are available on every plan (including Free). Recording
            about yourself is free; finishing an archive for someone
            you love is the {OTHER_IDENTITY_CREATE_PRICE_LABEL}{" "}
            one-time charge, and every redemption requires the{" "}
            {INHERITED_SLOT_PRICE_LABEL} one-time inherit-slot purchase
            described above (see Section 4).
          </li>
          <li>
            <strong>chapter3five does not currently offer a free trial
            of any paid plan.</strong> The Free tier is real and permanent
            — Adrian is available without payment for as long as your
            account exists. If we ever introduce a trial in the future,
            we will describe it here before making it available.
          </li>
        </ul>
        <p>
          Subscriptions are billed monthly in advance through Stripe and
          renew automatically until you cancel. You can cancel any time
          from your account settings; cancellation takes effect at the
          end of the current billing period. We may change prices with
          at least 30 days&rsquo; email notice; changes apply from your
          next billing period, and if you don&rsquo;t agree, you may
          cancel before they take effect.
        </p>
        <p>
          <strong>Moving down a tier</strong> (for example from Pro to
          Basic) takes effect at the end of your current billing period
          — you keep everything you paid for until the day you paid
          through. A downgrade never deletes your identities: if you
          have more than the lower plan includes, you can keep talking
          to the ones you have, and creating new ones waits until you
          are back under that plan&rsquo;s limits.
        </p>
        {/* WHO BILLS YOU. This paragraph used to say billing was Stripe
            for everyone, that everything was "handled at chapter3five.app",
            and that "We don't bill through Apple or Google" — all false
            once the apps began selling through StoreKit and Google Play
            Billing, and, inside the shipped app, prohibited purchase
            steering under App Store Guideline 3.1.1 and Google Play's
            Payments policy. It also sent Apple buyers to us for refunds
            they can only get from Apple. Kept in step with the mobile
            copy in app/legal/terms.tsx. */}
        <p>
          <strong>Who bills you depends on where you signed up.</strong>{" "}
          If you subscribed on this website, your subscription is billed
          by us through Stripe, and plan changes and cancellations are
          handled at{" "}
          <a
            href="https://chapter3five.app"
            className="text-coral-strong hover:underline"
          >
            chapter3five.app
          </a>
          .
        </p>
        <p>
          If you subscribed inside our iPhone or Android app, that
          subscription is sold and billed by Apple or Google, not by us.
          It renews through your Apple ID or Google account, you cancel
          it in that account&rsquo;s own subscription settings, and any
          refund is requested from Apple or Google &mdash; we cannot
          issue one on their behalf. Whichever way you signed up, the
          plan and the price are the same: {BASIC_TIER_LABEL} at{" "}
          {BASIC_MONTHLY_PRICE_LABEL}/month and Pro at{" "}
          {MONTHLY_PRICE_LABEL}/month, and you are never billed twice for
          the same account.
        </p>
        <p>
          <strong>Payments are non-refundable</strong>, except where the law
          requires otherwise. In particular, no refund (full or partial) is
          issued when:
        </p>
        <ul>
          <li>
            you <strong>cancel mid-month</strong> — you keep access until the
            end of the billing period you paid for;
          </li>
          <li>
            an <strong>identity blocks you</strong> for the conduct described
            in Section 9 — neither that identity&rsquo;s share of the plan
            nor the month&rsquo;s fee is refunded. Blocks are always
            temporary (a cool-off, then a check-in from the identity),
            and this rule <strong>never applies to inherited legacy
            identities</strong> — a legacy archive is content someone
            left you, and we won&rsquo;t take it away over conduct in the
            chat; or
          </li>
          <li>
            we <strong>suspend or terminate your account for abuse</strong>{" "}
            under Section 10.
          </li>
        </ul>
        <p>
          Deleting your account is separate from cancelling: deletion is
          subject to the 30-day grace window described in our Privacy
          Policy, during which you can restore your account before it is
          permanently erased.
        </p>
        <p>
          <strong>Your companions are made once per subscription — there
          is no redo.</strong> When you subscribe, your plan&rsquo;s
          companions are created for you a single time, tied to that
          subscription. Deleting an identity never frees its slot, and
          deleting your <em>account</em> permanently destroys the
          identities in it. If you delete your account while your store
          subscription is still active, the subscription itself is
          unaffected (Apple or Google keep billing it until you cancel it
          in <em>their</em> settings), and signing up again can restore
          the subscription&rsquo;s plan and monthly usage to your new
          account — but it does <strong>not</strong> recreate companions
          the subscription already made. They were yours, and they are
          gone. Creating new accounts to re-roll companions under the
          same subscription doesn&rsquo;t work, by design.
        </p>
        <p>
          If payment fails, we&rsquo;ll notify you and retry. If an account
          remains unpaid, we may suspend paid features, and we may delete the
          account and its data after giving you <strong>at least 30
          days&rsquo; notice</strong> by email. Deletion is permanent — see
          the Privacy Policy for what happens to legacy identities.
        </p>
      </LegalSection>

      <LegalSection id="conduct" number={9} title="How you agree to behave">
        <p>
          chapter3five is a warm place, and we intend to keep it that way.
          Our{" "}
          <a
            href="/guidelines"
            className="font-semibold underline underline-offset-4"
          >
            Community Guidelines
          </a>{" "}
          are part of these Terms and describe what is and isn&rsquo;t
          allowed — in short: no violence or content encouraging harm, no
          sexual content involving minors under any circumstances, no
          harassment, no impersonating real people without their permission,
          and no spam or commercial misuse. You also agree not to reverse
          engineer the service, probe or breach its security, scrape it, use
          it to build a competing dataset, or access it by automated means
          except through interfaces we provide.
        </p>
        <p>
          <strong>Photos and likeness — the hard line.</strong> When you
          create a companion from a photo, you are promising that the
          photo is <strong>of you</strong>, or of someone who{" "}
          <strong>gave you permission</strong> to use it. Do not upload
          public figures, celebrities, or anyone who has not agreed —
          living or dead. A companion is not a way to make a version of
          someone who never consented to exist here.
        </p>
        <p>
          If we learn that an identity was built from someone&rsquo;s
          likeness without permission — because it is reported, because
          the person or their family contacts us, or because we find it
          ourselves — <strong>we delete that identity</strong>, and{" "}
          <strong>no refund is issued</strong> for it, for any slot it
          consumed, or for the month. Repeated violations end the
          account. Anyone can report an identity from inside the app by
          tapping its portrait, and a person reviews every report.
        </p>
        <p>
          <strong>Community standards enforcement — identities can block
          you.</strong> Identities can and will end conversations with users
          who repeatedly abuse them, including persistent verbal aggression,
          sexual pressure after refusal, attempts to force the identity out
          of character, and hate speech. When an identity blocks you:
        </p>
        <ul>
          <li>the conversation ends and no new messages are accepted;</li>
          <li>
            that identity is <strong>permanently unavailable to you</strong>;
            and
          </li>
          <li>
            <strong>no refund is issued</strong> — not for that identity, and
            not for the month (see Section 8).
          </li>
        </ul>
        <p>
          A block by one identity does not by itself suspend your account,
          but the conduct that caused it may also count against the
          enforcement ladder in the Community Guidelines.
        </p>
      </LegalSection>

      <LegalSection
        id="termination"
        number={10}
        title="Suspension and termination"
      >
        <p>
          You can stop using chapter3five and delete your account at any
          time. We may suspend or terminate an account that violates these
          Terms or the Community Guidelines — using the enforcement ladder
          described in the Guidelines for most violations, and immediately
          and permanently for severe ones (such as any sexual content
          involving minors). We may also suspend or discontinue parts of the
          service where reasonably necessary, and delete accounts for
          non-payment as described in Section 8.
        </p>
        <p>
          Sections of these Terms that by their nature should survive
          termination — including Sections 4, 7, and 11 through 17 — survive
          it.
        </p>
      </LegalSection>

      <LegalSection id="disclaimers" number={11} title="Disclaimers">
        <p>
          We work hard on chapter3five, and we also have to be honest about
          the limits of software. TO THE FULLEST EXTENT PERMITTED BY LAW, THE
          SERVICE IS PROVIDED <strong>&quot;AS IS&quot; AND &quot;AS
          AVAILABLE,&quot;</strong> WITHOUT WARRANTIES OF ANY KIND, EXPRESS
          OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT
          THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR
          THAT ANY COMPANION&rsquo;S OUTPUT WILL BE ACCURATE, APPROPRIATE, OR
          EMOTIONALLY WHAT YOU HOPED FOR. AI-GENERATED TEXT IS PROBABILISTIC
          AND MAY SOMETIMES BE WRONG OR UPSETTING DESPITE OUR SAFEGUARDS.
        </p>
      </LegalSection>

      <LegalSection
        id="liability"
        number={12}
        title="Limitation of liability"
      >
        <p>
          TO THE FULLEST EXTENT PERMITTED BY LAW: (a) CHAPTER3FIVE AND ITS
          OFFICERS, EMPLOYEES, AND SUPPLIERS WILL NOT BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR
          PUNITIVE DAMAGES, OR FOR LOST PROFITS, LOST DATA, LOSS OF GOODWILL,
          OR EMOTIONAL DISTRESS, ARISING FROM OR RELATING TO THE SERVICE,
          EVEN IF ADVISED OF THE POSSIBILITY; AND (b) OUR TOTAL AGGREGATE
          LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED
          THE GREATER OF <strong>$100</strong> OR THE AMOUNTS YOU PAID US IN
          THE <strong>TWELVE MONTHS</strong> BEFORE THE CLAIM AROSE.
        </p>
        <p>
          Some jurisdictions do not allow certain limitations, so parts of
          this section may not apply to you; in that case our liability is
          limited to the smallest extent the law allows. Nothing in these
          Terms limits liability that cannot lawfully be limited, such as for
          our own fraud or willful misconduct.
        </p>
      </LegalSection>

      <LegalSection
        id="indemnification"
        number={13}
        title="Indemnification"
      >
        <p>
          You agree to indemnify and hold harmless chapter3five and its
          officers, employees, and agents from claims, damages, liabilities,
          and reasonable expenses (including attorneys&rsquo; fees) arising
          out of (a) content you submit to the service, (b) your violation of
          these Terms or the Community Guidelines, or (c) your violation of
          another person&rsquo;s rights — including recording content about,
          or creating a companion of, a person without the right to do so.
        </p>
      </LegalSection>

      <LegalSection
        id="disputes"
        number={14}
        title="Arbitration and class action waiver"
      >
        <p>
          <strong>Please read this section carefully — it affects your
          rights.</strong> Before filing any claim, you agree to first email
          us at hello@chapter3five.app and give us 60 days to try to resolve
          it informally. Most things can be fixed by two people talking.
        </p>
        <p>
          If we can&rsquo;t resolve it, you and chapter3five agree that any
          dispute arising out of or relating to these Terms or the service
          will be resolved by <strong>binding individual arbitration</strong>{" "}
          administered by the American Arbitration Association under its
          Consumer Arbitration Rules, rather than in court — except that
          either party may bring an individual claim in small claims court,
          or seek injunctive relief for infringement or misuse of
          intellectual property. The arbitration will be conducted in
          English, and the arbitrator&rsquo;s decision may be entered in any
          court of competent jurisdiction.
        </p>
        <p>
          <strong>CLASS ACTION WAIVER:</strong> ALL CLAIMS MUST BE BROUGHT IN
          A PARTY&rsquo;S INDIVIDUAL CAPACITY, NOT AS A PLAINTIFF OR CLASS
          MEMBER IN ANY PURPORTED CLASS, CONSOLIDATED, OR REPRESENTATIVE
          PROCEEDING, AND THE ARBITRATOR MAY NOT CONSOLIDATE CLAIMS OR
          PRESIDE OVER ANY FORM OF REPRESENTATIVE PROCEEDING. You may opt out
          of this arbitration agreement by emailing hello@chapter3five.app
          within 30 days of first accepting these Terms, with the subject
          line &quot;Arbitration opt-out.&quot;
        </p>
      </LegalSection>

      <LegalSection id="governing-law" number={15} title="Governing law">
        <p>
          These Terms are governed by the laws of the{" "}
          <strong>Commonwealth of Pennsylvania</strong>, without regard to
          conflict of laws principles. For any matter not subject to
          arbitration, you and chapter3five consent to the exclusive
          jurisdiction of the state and federal courts located in Northampton
          County, Pennsylvania.
        </p>
      </LegalSection>

      <LegalSection id="changes" number={16} title="Changes to these terms">
        <p>
          We may update these Terms from time to time. If we make a material
          change, we will email the address on your account at least{" "}
          <strong>30 days before the change takes effect</strong> and update
          the date at the top of this page. If you keep using chapter3five
          after the change takes effect, that means you accept it; if you
          don&rsquo;t accept it, you may close your account before the
          effective date and (if you prepaid) we&rsquo;ll refund the unused
          portion of your subscription.
        </p>
      </LegalSection>

      <LegalSection
        id="misc"
        number={17}
        title="Severability and everything else"
      >
        <p>
          If any provision of these Terms is found unenforceable, it will be
          enforced to the maximum extent permitted and the rest of the Terms
          remain in full force — except that if the class action waiver in
          Section 14 is found unenforceable as to a particular claim, that
          claim (and only that claim) must proceed in court rather than
          arbitration. These Terms, the Privacy Policy, and the Community
          Guidelines are the entire agreement between you and chapter3five
          about the service. You may not assign this agreement without our
          consent; we may assign it in connection with a merger, acquisition,
          or sale of assets, and will notify you if we do. Our failure to
          enforce a provision is not a waiver of it. Neither party is liable
          for delays caused by events beyond its reasonable control.
        </p>
      </LegalSection>

      <LegalSection id="contact" number={18} title="How to reach us">
        <p>
          For anything about these Terms:{" "}
          <a
            href="mailto:hello@chapter3five.app"
            className="font-semibold underline underline-offset-4"
          >
            hello@chapter3five.app
          </a>
          . For privacy and data requests:{" "}
          <a
            href="mailto:privacy@chapter3five.app"
            className="font-semibold underline underline-offset-4"
          >
            privacy@chapter3five.app
          </a>
          . To report a safety concern:{" "}
          <a
            href="mailto:safety@chapter3five.app"
            className="font-semibold underline underline-offset-4"
          >
            safety@chapter3five.app
          </a>
          .
        </p>
      </LegalSection>
    </LegalShell>
  );
}
