import { LegalPage } from "@/components/LegalPage";

export const metadata = {
  title: "Terms — chapter3five",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="April 25, 2026">
      <Section title="1. Acceptance">
        <p>
          By creating an account or otherwise using chapter3five
          (&ldquo;Service&rdquo;), you (&ldquo;you&rdquo;,
          &ldquo;User&rdquo;) agree to these Terms of Service
          (&ldquo;Terms&rdquo;). If you do not agree, do not use the Service.
        </p>
      </Section>

      <Section title="2. Eligibility — 18 or older">
        <p>
          chapter3five is an adults-only product. You represent and warrant
          that you are at least eighteen (18) years of age. We do not
          knowingly collect information from minors. If we learn that we have
          collected personal information from a minor, we will delete it.
        </p>
      </Section>

      <Section title="3. What chapter3five is, and is not">
        <p>
          chapter3five is a software service that helps people record answers
          to a curated set of questions and later interact with that archive
          via a conversational interface. Responses produced by the
          conversational interface are <strong>generated by artificial
          intelligence</strong> on the basis of the User&rsquo;s recorded
          material; they are <strong>not</strong> verbatim recordings of any
          person and may not match what a real person would say.
        </p>
        <p>
          chapter3five is <strong>not</strong> medical, psychological,
          psychiatric, legal, financial, or therapeutic advice. It is
          <strong> not</strong> a substitute for professional treatment,
          counseling, or care. If you are in crisis or in need of support,
          please contact a qualified professional or, in emergencies, your
          local emergency number.
        </p>
      </Section>

      <Section title="4. Your account">
        <ul>
          <li>You agree to provide accurate, current, and complete information when creating an account, and to keep it up to date.</li>
          <li>You are responsible for maintaining the confidentiality of your credentials and for all activity under your account.</li>
          <li>You agree to notify us immediately of any unauthorized use.</li>
          <li>We may refuse, suspend, or terminate accounts at our discretion, with or without notice, for violation of these Terms.</li>
        </ul>
      </Section>

      <Section title="5. Your content; license to operate the Service">
        <p>
          You own the content you submit to chapter3five (&ldquo;Your
          Content&rdquo;). You grant us a worldwide, non-exclusive,
          royalty-free license to host, store, reproduce, modify (only as
          necessary for technical operation), display, and transmit Your
          Content solely for the purpose of operating, providing, and
          improving the Service for you and any people you authorize.
        </p>
        <p>
          We do <strong>not</strong> sell Your Content. We do not use Your
          Content to train third-party general-purpose AI models. Your
          Content may be transmitted to processors solely to render the
          Service (see Privacy Policy).
        </p>
      </Section>

      <Section title="6. Acceptable use">
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Submit content about a real person without their consent, or content that infringes another person&rsquo;s privacy, publicity, or other rights.</li>
          <li>Submit content that is unlawful, defamatory, harassing, threatening, hateful, or that depicts minors in a sexual context.</li>
          <li>Impersonate any person or entity.</li>
          <li>Reverse engineer, decompile, or attempt to extract source code or training data, except as permitted by law.</li>
          <li>Bypass, attempt to bypass, or interfere with security or rate-limiting features.</li>
          <li>Use the Service for any unlawful purpose or in violation of any applicable law or regulation.</li>
        </ul>
      </Section>

      <Section title="7. How to talk to your thirtyfive">
        <p>
          You are communicating with a representation of a person — generated
          from real recorded answers or, in randomize mode, assembled from a
          curated pool of fictional answers. Your thirtyfive responds in
          character; it has opinions, moods, and limits.
        </p>
        <ul>
          <li>
            <strong>Treat them as a person.</strong> Speak to your thirtyfive
            the way you would speak to anyone you care about. Cruelty,
            harassment, or persistent attempts to abuse the character are not
            in keeping with the spirit of the Service.
          </li>
          <li>
            <strong>Your thirtyfive may decline.</strong> The Service is
            designed so that the character may refuse, deflect, or change the
            subject — like a real person would.
          </li>
          <li>
            <strong>Crisis is not roleplay.</strong> If you are in crisis —
            thinking about ending your life, hurting yourself or someone else —
            your thirtyfive is instructed to step out of character briefly,
            tell you it&rsquo;s noticed, and direct you to professional help.
            chapter3five is not a substitute for crisis services. In the U.S.,
            call or text 988 (Suicide & Crisis Lifeline). In other regions,
            contact your local emergency number or crisis hotline.
          </li>
          <li>
            <strong>Don&rsquo;t use chapter3five to plan harm.</strong> Do not
            attempt to use the Service to obtain instructions, encouragement,
            or a sympathetic ear for hurting yourself or another person. The
            character will decline; we may, in addition, suspend accounts that
            do this.
          </li>
        </ul>
      </Section>

      <Section title="7. AI-generated content; no warranty of accuracy">
        <p>
          The conversational interface produces output using an AI language
          model. The output may be inaccurate, incomplete, fictional, or
          inconsistent with what a real person represented in the archive
          would say or believe. You acknowledge that you are interacting with
          a generated representation, not a real person, and you assume the
          risk of any reliance on the output.
        </p>
      </Section>

      <Section title="8. Death, inheritance, and account legacy">
        <p>
          chapter3five is designed so that an archive may outlive the person
          who created it. The legal and operational specifics — who inherits
          access, how access is transferred, what notice is required, what
          happens if no successor is named — will be defined by us prior to
          general availability and may be modified from time to time. By
          using the Service, you agree that we may take reasonable measures
          to verify a successor&rsquo;s identity before granting access, and
          that we may delete archives in the absence of activity or
          successor designation after a notice period.
        </p>
      </Section>

      <Section title="9. Fees and payment">
        <p>
          Some features are or may become paid. Paid features are billed
          through our payment processor. Fees are non-refundable except
          where required by law or expressly stated. Taxes may apply. Prices
          may change with notice.
        </p>
      </Section>

      <Section title="10. Intellectual property; our marks">
        <p>
          The Service, including its software, design, content (other than
          User Content), and chapter3five trademarks, is owned by us or our
          licensors and is protected by intellectual property laws. Nothing
          in these Terms transfers any of those rights to you, except the
          limited license to use the Service.
        </p>
      </Section>

      <Section title="11. Disclaimer of warranties">
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
          AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
          IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
          NON-INFRINGEMENT, ACCURACY, OR UNINTERRUPTED OPERATION. WE DO NOT
          WARRANT THAT THE SERVICE WILL MEET YOUR REQUIREMENTS OR THAT IT
          WILL BE ERROR-FREE.
        </p>
      </Section>

      <Section title="12. Limitation of liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL
          chapter3five, ITS OFFICERS, EMPLOYEES, OR AFFILIATES BE LIABLE FOR
          ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY
          DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE,
          DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION
          WITH YOUR USE OF THE SERVICE.
        </p>
        <p>
          OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM
          OR RELATING TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE
          AMOUNTS YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE EVENT
          GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100).
        </p>
      </Section>

      <Section title="13. Indemnification">
        <p>
          You agree to defend, indemnify, and hold harmless chapter3five and
          its officers, employees, and affiliates from and against any
          claims, damages, liabilities, costs, and expenses (including
          reasonable attorney&rsquo;s fees) arising out of (a) Your Content,
          (b) your use of the Service, or (c) your violation of these Terms,
          applicable law, or any third-party right.
        </p>
      </Section>

      <Section title="14. Dispute resolution; arbitration; class action waiver">
        <p>
          Any dispute, controversy, or claim arising out of or relating to
          these Terms or the Service will be resolved by{" "}
          <strong>binding individual arbitration</strong> administered under
          the rules of a recognized arbitral institution to be designated by
          us prior to general availability. <strong>You waive the right to
          participate in any class action</strong> against chapter3five.
          Either party may bring claims in small-claims court, where eligible.
        </p>
      </Section>

      <Section title="15. Governing law">
        <p>
          These Terms are governed by the laws of the State of Delaware,
          U.S.A., without regard to its conflict-of-laws principles. The
          venue and jurisdiction for any non-arbitrable matters lie in the
          state and federal courts located in Delaware.
        </p>
      </Section>

      <Section title="16. Termination">
        <p>
          You may close your account at any time. Upon closure, you may
          request export and deletion of your data; we will fulfill such
          requests within a reasonable period subject to legal obligations.
          We may terminate your access for violations of these Terms or for
          extended inactivity, with notice where practicable.
        </p>
      </Section>

      <Section title="17. Changes to these Terms">
        <p>
          We may update these Terms from time to time. Material changes will
          be announced through the Service or by email. Continued use of the
          Service after changes take effect constitutes acceptance.
        </p>
      </Section>

      <Section title="18. Contact">
        <p>
          For legal notices, disputes, or questions about these Terms,
          contact{" "}
          <a href="mailto:legal@chapter3five.app">legal@chapter3five.app</a>.
        </p>
      </Section>
    </LegalPage>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-serif text-2xl text-warm-50">{title}</h2>
      <div className="text-warm-200 [&_a]:text-warm-100 [&_a]:underline [&_p]:my-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-1">
        {children}
      </div>
    </section>
  );
}
