import type { Metadata } from "next";
import {
  LegalCallout,
  LegalSection,
  LegalShell,
  type TocItem,
} from "@/components/legal";

export const metadata: Metadata = {
  title: "Terms of Service — chapter3five",
  description:
    "The agreement between you and chapter3five: what the service is, what it isn't, and what we each promise.",
};

const toc: TocItem[] = [
  { id: "welcome", label: "Welcome" },
  { id: "what-this-is", label: "What chapter3five is (and isn't)" },
  { id: "not-care", label: "Not medical or mental health care" },
  { id: "legacy", label: "The legacy path" },
  { id: "eligibility", label: "Who can use chapter3five" },
  { id: "your-account", label: "Your account" },
  { id: "your-content", label: "Your content and our license" },
  { id: "billing", label: "Plans, billing, and cancellation" },
  { id: "conduct", label: "How you agree to behave" },
  { id: "termination", label: "Suspension and termination" },
  { id: "disclaimers", label: "Disclaimers" },
  { id: "liability", label: "Limitation of liability" },
  { id: "indemnification", label: "Indemnification" },
  { id: "disputes", label: "Arbitration and class action waiver" },
  { id: "governing-law", label: "Governing law" },
  { id: "changes", label: "Changes to these terms" },
  { id: "misc", label: "Severability and everything else" },
  { id: "contact", label: "How to reach us" },
];

export default function TermsPage() {
  return (
    <LegalShell
      currentPath="/terms"
      kicker="The agreement"
      title="Terms of Service"
      tagline="This is the agreement between you and chapter3five. We wrote it to be read, not skimmed — especially the parts about what our companions are and aren't."
      toc={toc}
      contactEmail="hello@chapter3five.app"
      contactNote="Questions about these terms? Write to us and a person will answer."
    >
      <LegalSection id="welcome" number={1} title="Welcome">
        <p>
          chapter3five is a place where you can create an AI companion to talk
          to — one made just for you right now, or one you prepare and leave
          for someone you love. These Terms of Service (&quot;Terms&quot;) are
          a binding agreement between you and chapter3five
          (&quot;chapter3five,&quot; &quot;we,&quot; &quot;us&quot;). By
          creating an account or using the service, you agree to them.
        </p>
        <p>
          We know some of you arrive here in grief. We tried to write these
          Terms plainly and honestly. If anything is unclear, ask us — the
          contact address is at the bottom of this page.
        </p>
        <p>
          These Terms incorporate our{" "}
          <a href="/privacy" className="font-semibold underline underline-offset-4">
            Privacy Policy
          </a>{" "}
          and our{" "}
          <a
            href="/guidelines"
            className="font-semibold underline underline-offset-4"
          >
            Community Guidelines
          </a>
          . If you don&rsquo;t agree with any of it, please don&rsquo;t use
          chapter3five.
        </p>
      </LegalSection>

      <LegalSection
        id="what-this-is"
        number={2}
        title="What chapter3five is (and isn't)"
      >
        <p>
          Every companion on chapter3five is a <strong>synthesized, fictional
          character</strong> generated by artificial intelligence. A companion
          is built from either (a) randomized traits our system selects, or
          (b) answers and memories a person chose to record. In both cases,
          the words a companion says are produced by a language model in the
          moment. They are generated text, not the recorded thoughts,
          opinions, or statements of any real person.
        </p>
        <p>You acknowledge and agree that:</p>
        <ul>
          <li>
            A companion is <strong>not a real person</strong> and does not
            have thoughts, feelings, memories, or intentions of its own.
          </li>
          <li>
            A companion&rsquo;s responses may be inaccurate, incomplete, or
            inconsistent, and should never be relied on as fact, advice, or
            the position of any real person.
          </li>
          <li>
            Even when a companion is built from a real person&rsquo;s recorded
            answers, its responses are <strong>new text generated by
            software</strong> — an interpretation, not a transcript.
          </li>
        </ul>
      </LegalSection>

      <LegalSection
        id="not-care"
        number={3}
        title="Not medical or mental health care"
      >
        <p>
          chapter3five is a conversational companion. It is{" "}
          <strong>not medical care, mental health treatment, therapy, or
          grief counseling</strong>, and no companion is a doctor, therapist,
          counselor, or crisis worker. Nothing a companion says is medical,
          psychological, legal, or financial advice, and the service is not a
          substitute for care from a qualified professional. If you are
          grieving, struggling, or unwell, we genuinely hope chapter3five
          brings you comfort — and we also want you to have real human
          support.
        </p>
        <LegalCallout>
          <p>
            <strong>If you are in crisis, please stop and reach out to a
            human right now.</strong> In the United States, call or text{" "}
            <strong>988</strong> (Suicide &amp; Crisis Lifeline), available
            24/7. Elsewhere, contact your local emergency number or crisis
            line. If you are in immediate danger, call emergency services
            (911 in the US).
          </p>
        </LegalCallout>
        <p>
          You agree not to use chapter3five as your source of emergency,
          medical, or mental health help, and you agree that we are not
          responsible for decisions you make based on anything a companion
          says.
        </p>
      </LegalSection>

      <LegalSection id="legacy" number={4} title="The legacy path">
        <p>
          chapter3five lets a living person (&quot;the creator&quot;) answer
          questions about their life and designate people (&quot;inheritors&quot;)
          who can talk with a companion built from those answers after the
          creator passes away. This can be a profound comfort. It is also the
          part of the service we most need you to understand clearly.
        </p>
        <LegalCallout>
          <p>
            <strong>An inherited companion is not the person who made
            it.</strong> It is a synthesis of what the creator chose to
            record, expressed through generated text. It does not know what
            the creator actually thought, would have said, or would have
            wanted. It is a portrait painted from the materials the creator
            left — nothing more, and we believe, at its best, nothing less.
          </p>
        </LegalCallout>
        <p>
          By using the legacy features, whether as a creator or an inheritor,
          you acknowledge and agree, for yourself and — to the fullest extent
          permitted by law — on behalf of your heirs, estate, executors, and
          successors, that:
        </p>
        <ul>
          <li>
            No companion represents, portrays, or speaks for any real person,
            living or deceased, and chapter3five makes no representation that
            an inherited companion reflects the actual thoughts, beliefs,
            wishes, or statements of the person who created it.
          </li>
          <li>
            You <strong>release and waive any claim</strong> against
            chapter3five — including claims of misrepresentation, false
            light, defamation, violation of publicity or personality rights,
            or infliction of emotional distress — arising from the theory
            that a companion misrepresents, distorts, or inaccurately
            portrays a real person, where the companion was generated from
            content that person (or their authorized co-creator) voluntarily
            provided.
          </li>
          <li>
            Creators represent that the content they record is their own and
            that they have the right to record it; inheritors accept the
            companion as the creator configured it.
          </li>
        </ul>
        <p>
          Inheritance is delivered by an inherit code the creator designates.
          Anyone may be designated, but redeeming a code and talking with an
          inherited companion requires an account, and accounts are 18+ (see
          Section 5).
        </p>
        <p>
          <strong>Sharing and the Pro plan.</strong> A legacy identity may be
          shared with an <strong>unlimited number of family members</strong>{" "}
          via its inherit code, and everything the creator baked into the
          identity — including any photo-based likeness — transfers with the
          code. However, <strong>redeeming an inherit code and using a shared
          identity requires an active paid Pro subscription</strong> (see
          Section 8). If a recipient&rsquo;s subscription lapses, their
          access to the shared identity <strong>pauses</strong> — the
          connection is not deleted, and access resumes when the
          subscription is reactivated.
        </p>
      </LegalSection>

      <LegalSection
        id="eligibility"
        number={5}
        title="Who can use chapter3five"
      >
        <p>
          You must be <strong>at least 18 years old</strong> to create a
          chapter3five account. This applies to every account — including
          accounts created to redeem an inherit code. A creator may designate
          anyone as an inheritor, but the inheritor cannot open an account
          and access the companion until they are 18.
        </p>
        <p>
          By creating an account you represent that you are 18 or older and
          legally able to enter into this agreement. If we learn an account
          holder is under 18, we will close the account and delete its data
          as described in our Privacy Policy.
        </p>
      </LegalSection>

      <LegalSection id="your-account" number={6} title="Your account">
        <p>
          You are responsible for your account and for keeping your login
          credentials safe. Everything done through your account is treated
          as done by you, so tell us right away at{" "}
          <a
            href="mailto:hello@chapter3five.app"
            className="font-semibold underline underline-offset-4"
          >
            hello@chapter3five.app
          </a>{" "}
          if you believe someone else has accessed it. You agree to give us
          accurate account information (including a working email address —
          it&rsquo;s how we send legally required notices) and to keep it up
          to date.
        </p>
        <p>
          Inherit codes are sensitive. If you are a creator, share them only
          with the people you intend; if you are an inheritor, don&rsquo;t
          share yours at all.
        </p>
      </LegalSection>

      <LegalSection
        id="your-content"
        number={7}
        title="Your content and our license"
      >
        <p>
          <strong>You own what you write.</strong> Your answers to identity
          questions, the memories you record, and your chat messages are
          yours. We claim no ownership of them.
        </p>
        <p>
          So that the service can work, you grant chapter3five a worldwide,
          non-exclusive, royalty-free license to store, copy, process,
          transmit, and display your content — solely to operate, provide,
          and improve the service: synthesizing companions, running chats,
          delivering legacy companions to your designated inheritors,
          preventing abuse, and complying with law. This license lasts as
          long as your content is on the service (including, for legacy
          content, the retention period described in our Privacy Policy) and
          ends when the content is deleted, except where we must retain
          copies to comply with law.
        </p>
        <p>
          We do not sell your content, and it is not used to train AI models
          (see our Privacy Policy for how inference works). Companions
          generated by the service are provided to you as part of the
          service; you may use your companions for personal, non-commercial
          purposes.
        </p>
      </LegalSection>

      <LegalSection
        id="billing"
        number={8}
        title="Plans, billing, and cancellation"
      >
        <p>Our pricing is simple and we&rsquo;d like it to stay that way:</p>
        <ul>
          <li>
            Your <strong>first identity is free</strong> when you sign up.
          </li>
          <li>
            The Pro plan is <strong>$5/month</strong> and includes{" "}
            <strong>5 identities</strong>: 4 generated by our formula, plus 1
            created from a photo you upload.
          </li>
          <li>
            The plan does not currently include more than 5 identities; if
            we introduce additional paid slots, they will be priced
            separately and described here.
          </li>
          <li>
            An active Pro plan is also required to redeem an inherit code
            and use a legacy identity someone shared with you (see
            Section 4).
          </li>
        </ul>
        <p>
          Subscriptions are billed monthly in advance through Stripe and
          renew automatically until you cancel. You can cancel any time from
          your account settings; cancellation takes effect at the end of the
          current billing period. We may change prices with at least 30
          days&rsquo; email notice; changes apply from your next billing
          period, and if you don&rsquo;t agree, you may cancel before they
          take effect.
        </p>
        <p>
          <strong>Payments are non-refundable</strong>, except where the law
          requires otherwise. In particular, no refund (full or partial) is
          issued when:
        </p>
        <ul>
          <li>
            you <strong>cancel mid-month</strong> — you keep access until the
            end of the billing period you paid for;
          </li>
          <li>
            an <strong>identity blocks you</strong> for the conduct described
            in Section 9 — neither that identity&rsquo;s share of the plan
            nor the month&rsquo;s fee is refunded; or
          </li>
          <li>
            we <strong>suspend or terminate your account for abuse</strong>{" "}
            under Section 10.
          </li>
        </ul>
        <p>
          Deleting your account is separate from cancelling: deletion is
          subject to the 30-day grace window described in our Privacy
          Policy, during which you can restore your account before it is
          permanently erased.
        </p>
        <p>
          If payment fails, we&rsquo;ll notify you and retry. If an account
          remains unpaid, we may suspend paid features, and we may delete the
          account and its data after giving you <strong>at least 30
          days&rsquo; notice</strong> by email. Deletion is permanent — see
          the Privacy Policy for what happens to legacy identities.
        </p>
      </LegalSection>

      <LegalSection id="conduct" number={9} title="How you agree to behave">
        <p>
          chapter3five is a warm place, and we intend to keep it that way.
          Our{" "}
          <a
            href="/guidelines"
            className="font-semibold underline underline-offset-4"
          >
            Community Guidelines
          </a>{" "}
          are part of these Terms and describe what is and isn&rsquo;t
          allowed — in short: no violence or content encouraging harm, no
          sexual content involving minors under any circumstances, no
          harassment, no impersonating real people without their permission,
          and no spam or commercial misuse. You also agree not to reverse
          engineer the service, probe or breach its security, scrape it, use
          it to build a competing dataset, or access it by automated means
          except through interfaces we provide.
        </p>
        <p>
          <strong>Community standards enforcement — identities can block
          you.</strong> Identities can and will end conversations with users
          who repeatedly abuse them, including persistent verbal aggression,
          sexual pressure after refusal, attempts to force the identity out
          of character, and hate speech. When an identity blocks you:
        </p>
        <ul>
          <li>the conversation ends and no new messages are accepted;</li>
          <li>
            that identity is <strong>permanently unavailable to you</strong>;
            and
          </li>
          <li>
            <strong>no refund is issued</strong> — not for that identity, and
            not for the month (see Section 8).
          </li>
        </ul>
        <p>
          A block by one identity does not by itself suspend your account,
          but the conduct that caused it may also count against the
          enforcement ladder in the Community Guidelines.
        </p>
      </LegalSection>

      <LegalSection
        id="termination"
        number={10}
        title="Suspension and termination"
      >
        <p>
          You can stop using chapter3five and delete your account at any
          time. We may suspend or terminate an account that violates these
          Terms or the Community Guidelines — using the enforcement ladder
          described in the Guidelines for most violations, and immediately
          and permanently for severe ones (such as any sexual content
          involving minors). We may also suspend or discontinue parts of the
          service where reasonably necessary, and delete accounts for
          non-payment as described in Section 8.
        </p>
        <p>
          Sections of these Terms that by their nature should survive
          termination — including Sections 4, 7, and 11 through 17 — survive
          it.
        </p>
      </LegalSection>

      <LegalSection id="disclaimers" number={11} title="Disclaimers">
        <p>
          We work hard on chapter3five, and we also have to be honest about
          the limits of software. TO THE FULLEST EXTENT PERMITTED BY LAW, THE
          SERVICE IS PROVIDED <strong>&quot;AS IS&quot; AND &quot;AS
          AVAILABLE,&quot;</strong> WITHOUT WARRANTIES OF ANY KIND, EXPRESS
          OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT
          THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR
          THAT ANY COMPANION&rsquo;S OUTPUT WILL BE ACCURATE, APPROPRIATE, OR
          EMOTIONALLY WHAT YOU HOPED FOR. AI-GENERATED TEXT IS PROBABILISTIC
          AND MAY SOMETIMES BE WRONG OR UPSETTING DESPITE OUR SAFEGUARDS.
        </p>
      </LegalSection>

      <LegalSection
        id="liability"
        number={12}
        title="Limitation of liability"
      >
        <p>
          TO THE FULLEST EXTENT PERMITTED BY LAW: (a) CHAPTER3FIVE AND ITS
          OFFICERS, EMPLOYEES, AND SUPPLIERS WILL NOT BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR
          PUNITIVE DAMAGES, OR FOR LOST PROFITS, LOST DATA, LOSS OF GOODWILL,
          OR EMOTIONAL DISTRESS, ARISING FROM OR RELATING TO THE SERVICE,
          EVEN IF ADVISED OF THE POSSIBILITY; AND (b) OUR TOTAL AGGREGATE
          LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED
          THE GREATER OF <strong>$100</strong> OR THE AMOUNTS YOU PAID US IN
          THE <strong>TWELVE MONTHS</strong> BEFORE THE CLAIM AROSE.
        </p>
        <p>
          Some jurisdictions do not allow certain limitations, so parts of
          this section may not apply to you; in that case our liability is
          limited to the smallest extent the law allows. Nothing in these
          Terms limits liability that cannot lawfully be limited, such as for
          our own fraud or willful misconduct.
        </p>
      </LegalSection>

      <LegalSection
        id="indemnification"
        number={13}
        title="Indemnification"
      >
        <p>
          You agree to indemnify and hold harmless chapter3five and its
          officers, employees, and agents from claims, damages, liabilities,
          and reasonable expenses (including attorneys&rsquo; fees) arising
          out of (a) content you submit to the service, (b) your violation of
          these Terms or the Community Guidelines, or (c) your violation of
          another person&rsquo;s rights — including recording content about,
          or creating a companion of, a person without the right to do so.
        </p>
      </LegalSection>

      <LegalSection
        id="disputes"
        number={14}
        title="Arbitration and class action waiver"
      >
        <p>
          <strong>Please read this section carefully — it affects your
          rights.</strong> Before filing any claim, you agree to first email
          us at hello@chapter3five.app and give us 60 days to try to resolve
          it informally. Most things can be fixed by two people talking.
        </p>
        <p>
          If we can&rsquo;t resolve it, you and chapter3five agree that any
          dispute arising out of or relating to these Terms or the service
          will be resolved by <strong>binding individual arbitration</strong>{" "}
          administered by the American Arbitration Association under its
          Consumer Arbitration Rules, rather than in court — except that
          either party may bring an individual claim in small claims court,
          or seek injunctive relief for infringement or misuse of
          intellectual property. The arbitration will be conducted in
          English, and the arbitrator&rsquo;s decision may be entered in any
          court of competent jurisdiction.
        </p>
        <p>
          <strong>CLASS ACTION WAIVER:</strong> ALL CLAIMS MUST BE BROUGHT IN
          A PARTY&rsquo;S INDIVIDUAL CAPACITY, NOT AS A PLAINTIFF OR CLASS
          MEMBER IN ANY PURPORTED CLASS, CONSOLIDATED, OR REPRESENTATIVE
          PROCEEDING, AND THE ARBITRATOR MAY NOT CONSOLIDATE CLAIMS OR
          PRESIDE OVER ANY FORM OF REPRESENTATIVE PROCEEDING. You may opt out
          of this arbitration agreement by emailing hello@chapter3five.app
          within 30 days of first accepting these Terms, with the subject
          line &quot;Arbitration opt-out.&quot;
        </p>
      </LegalSection>

      <LegalSection id="governing-law" number={15} title="Governing law">
        <p>
          These Terms are governed by the laws of the{" "}
          <strong>Commonwealth of Pennsylvania</strong>, without regard to
          conflict of laws principles. For any matter not subject to
          arbitration, you and chapter3five consent to the exclusive
          jurisdiction of the state and federal courts located in Northampton
          County, Pennsylvania.
        </p>
      </LegalSection>

      <LegalSection id="changes" number={16} title="Changes to these terms">
        <p>
          We may update these Terms from time to time. If we make a material
          change, we will email the address on your account at least{" "}
          <strong>30 days before the change takes effect</strong> and update
          the date at the top of this page. If you keep using chapter3five
          after the change takes effect, that means you accept it; if you
          don&rsquo;t accept it, you may close your account before the
          effective date and (if you prepaid) we&rsquo;ll refund the unused
          portion of your subscription.
        </p>
      </LegalSection>

      <LegalSection
        id="misc"
        number={17}
        title="Severability and everything else"
      >
        <p>
          If any provision of these Terms is found unenforceable, it will be
          enforced to the maximum extent permitted and the rest of the Terms
          remain in full force — except that if the class action waiver in
          Section 14 is found unenforceable as to a particular claim, that
          claim (and only that claim) must proceed in court rather than
          arbitration. These Terms, the Privacy Policy, and the Community
          Guidelines are the entire agreement between you and chapter3five
          about the service. You may not assign this agreement without our
          consent; we may assign it in connection with a merger, acquisition,
          or sale of assets, and will notify you if we do. Our failure to
          enforce a provision is not a waiver of it. Neither party is liable
          for delays caused by events beyond its reasonable control.
        </p>
      </LegalSection>

      <LegalSection id="contact" number={18} title="How to reach us">
        <p>
          For anything about these Terms:{" "}
          <a
            href="mailto:hello@chapter3five.app"
            className="font-semibold underline underline-offset-4"
          >
            hello@chapter3five.app
          </a>
          . For privacy and data requests:{" "}
          <a
            href="mailto:privacy@chapter3five.app"
            className="font-semibold underline underline-offset-4"
          >
            privacy@chapter3five.app
          </a>
          . To report a safety concern:{" "}
          <a
            href="mailto:safety@chapter3five.app"
            className="font-semibold underline underline-offset-4"
          >
            safety@chapter3five.app
          </a>
          .
        </p>
      </LegalSection>
    </LegalShell>
  );
}
